version: 0.2

phases:
  install:
    commands:
      - echo "Install Phase"

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 037063405138.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build Started"
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 037063405138.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo "Push Image"
      - docker push 037063405138.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

artifacts:
  files:
    - '**/*'