apiVersion: v1
kind: Service

metadata:
  name: brain-task-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb

  selector:
    app: brain-task-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80